Explore BROWSER values and edge cases

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -136,19 +136,6 @@ runs:
           echo "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️ YOU MAY BE MISSING THE _ALKILN_INTERNAL_TESTS FLAG ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
         fi
         npm install --ignore-scripts --min-release-age=7 -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
-        BROWSER="$(
-          command -v google-chrome-stable ||
-          command -v google-chrome ||
-          command -v chromium-browser ||
-          command -v chromium ||
-          true
-        )"
-        if [[ -n "$BROWSER" ]]; then
-          echo "PUPPETEER_EXECUTABLE_PATH=$BROWSER" >> "$GITHUB_ENV"
-        else
-          rm -rf "$HOME/.cache/puppeteer"
-          node "$(npm root -g)/@suffolklitlab/alkiln/node_modules/puppeteer/install.mjs"
-        fi
 
     # For internal development, allow testing with more recent versions of ALKiln
     - name: "🔎 ALK0279 WARNING: Install recent version of ALKiln directly from npm"
@@ -165,6 +152,10 @@ runs:
           echo "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️ YOU MAY BE USING AN UNSAFE VERSION OF ALKILN ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
         fi
         npm install --ignore-scripts -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
+        
+    - name: "Install puppeteer's browser executable"
+      shell: bash
+      run: |
         BROWSER="$(
           command -v google-chrome-stable ||
           command -v google-chrome ||
@@ -172,9 +163,14 @@ runs:
           command -v chromium ||
           true
         )"
+        echo "BROWSER: $BROWSER"
+        set +e
+        echo -e "'-v' $( $BROWSER -v )"
+        set -e
         if [[ -n "$BROWSER" ]]; then
           echo "PUPPETEER_EXECUTABLE_PATH=$BROWSER" >> "$GITHUB_ENV"
         else
+          echo "Unable to find the browser executable. Cleaning puppeteer's cache and using its install.mjs directly."
           rm -rf "$HOME/.cache/puppeteer"
           node "$(npm root -g)/@suffolklitlab/alkiln/node_modules/puppeteer/install.mjs"
         fi
