Check if both installs running, reduces logs and actions for clarity

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -135,9 +135,9 @@ runs:
         if [[ $repo_name == *"ALKiln"* ]]; then
           echo "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️ YOU MAY BE MISSING THE _ALKILN_INTERNAL_TESTS FLAG ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
         fi
-        npm install --ignore-scripts --min-release-age=7 --loglevel=verbose -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
-        npm list -g puppeteer
-        npm rebuild -g puppeteer
+        # npm install --ignore-scripts --min-release-age=7 --loglevel=verbose -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
+        # npm list -g puppeteer
+        # npm rebuild -g puppeteer
 
     # For internal development, allow testing with more recent versions of ALKiln
     - name: "🔎 ALK0279 WARNING: Install recent version of ALKiln directly from npm"
@@ -154,157 +154,157 @@ runs:
         if [[ $repo_name != *"ALKiln"* ]]; then
           echo "⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️ YOU MAY BE USING AN UNSAFE VERSION OF ALKILN ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️"
         fi
-        npm install --ignore-scripts --loglevel=verbose -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
-        npm list -g puppeteer
-        npm rebuild -g puppeteer
+        # npm install --ignore-scripts --loglevel=verbose -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
+        # npm list -g puppeteer
+        # npm rebuild -g puppeteer
 
-    # Files prep
-    - shell: bash
-      env:
-        ARTIFACT_FOLDER: ${{ env.ARTIFACT_FOLDER }}
-      run: |
-        log="💡 ALK0275 INFO: Prepare repository test files"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
-        alkiln-artifacts --path="${{ env.ARTIFACT_FOLDER }}"
-        alkiln-validate
-        alkiln-generate
+    # # Files prep
+    # - shell: bash
+    #   env:
+    #     ARTIFACT_FOLDER: ${{ env.ARTIFACT_FOLDER }}
+    #   run: |
+    #     log="💡 ALK0275 INFO: Prepare repository test files"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
+    #     alkiln-artifacts --path="${{ env.ARTIFACT_FOLDER }}"
+    #     alkiln-validate
+    #     alkiln-generate
 
-    # Install package on playground
-    # Don't rely on the environment's version of python
-    - uses: actions/setup-python@v5
-      if: ${{ inputs.INSTALL_METHOD == 'playground' }}
-      with:
-        python-version: '3.10'
-    - name: "💡 ALK0027 INFO: Create a Project and install the package from GitHub"
-      if: ${{ inputs.INSTALL_METHOD == 'playground' }}
-      shell: bash
-      run: |
-        log="💡 ALK0027 INFO: Create a Project and install the package from GitHub"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
-        pip install "docassemblecli==$DOCASSEMBLECLI_VERSION"
-        alkiln-setup
-    - name: "🤕 ALK0028 ERROR: Unable to create a Project"
-      if: ${{ inputs.INSTALL_METHOD == 'playground' && failure() }}
-      shell: bash
-      run: |
-        # "🤕 ALK0028 ERROR: Unable to create a Project"
-        long_log="\n\n―――\n🤕 ALK0028 ERROR: Unable to create a Project on your server's testing account or pull your package into it. Check the messages above this line.\n\n"
-        echo -e "$long_log" >> "${{ env.DEBUG_PATH }}" && echo -e "$long_log"
+    # # Install package on playground
+    # # Don't rely on the environment's version of python
+    # - uses: actions/setup-python@v5
+    #   if: ${{ inputs.INSTALL_METHOD == 'playground' }}
+    #   with:
+    #     python-version: '3.10'
+    # - name: "💡 ALK0027 INFO: Create a Project and install the package from GitHub"
+    #   if: ${{ inputs.INSTALL_METHOD == 'playground' }}
+    #   shell: bash
+    #   run: |
+    #     log="💡 ALK0027 INFO: Create a Project and install the package from GitHub"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
+    #     pip install "docassemblecli==$DOCASSEMBLECLI_VERSION"
+    #     alkiln-setup
+    # - name: "🤕 ALK0028 ERROR: Unable to create a Project"
+    #   if: ${{ inputs.INSTALL_METHOD == 'playground' && failure() }}
+    #   shell: bash
+    #   run: |
+    #     # "🤕 ALK0028 ERROR: Unable to create a Project"
+    #     long_log="\n\n―――\n🤕 ALK0028 ERROR: Unable to create a Project on your server's testing account or pull your package into it. Check the messages above this line.\n\n"
+    #     echo -e "$long_log" >> "${{ env.DEBUG_PATH }}" && echo -e "$long_log"
 
-    # Server installation
-    - name: "💡 ALK0029 INFO: Try to install the GitHub package onto the GitHub sandbox server"
-      if: ${{ inputs.INSTALL_METHOD == 'server' }}
-      shell: bash
-      run: |
-        log="💡 ALK0029 INFO: Install the GitHub package onto the server"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
-        alkiln-server-install
-    - name: "🤕 ALK0030 ERROR: Unable to install the package on the GitHub sandbox server"
-      if: ${{ inputs.INSTALL_METHOD == 'server' && failure() }}
-      shell: bash
-      run: |
-        log="\n\n―――\n🤕 ALK0030 ERROR: Unable to install the package on the temporary GitHub docassemble server. Check the steps above this line.\n\n"
-        echo -e "$log" >> "${{ env.DEBUG_PATH }}" && echo -e "$log"
+    # # Server installation
+    # - name: "💡 ALK0029 INFO: Try to install the GitHub package onto the GitHub sandbox server"
+    #   if: ${{ inputs.INSTALL_METHOD == 'server' }}
+    #   shell: bash
+    #   run: |
+    #     log="💡 ALK0029 INFO: Install the GitHub package onto the server"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
+    #     alkiln-server-install
+    # - name: "🤕 ALK0030 ERROR: Unable to install the package on the GitHub sandbox server"
+    #   if: ${{ inputs.INSTALL_METHOD == 'server' && failure() }}
+    #   shell: bash
+    #   run: |
+    #     log="\n\n―――\n🤕 ALK0030 ERROR: Unable to install the package on the temporary GitHub docassemble server. Check the steps above this line.\n\n"
+    #     echo -e "$log" >> "${{ env.DEBUG_PATH }}" && echo -e "$log"
 
-    # run tests
-    - name: "💡 ALK0031 INFO: Run tests"
-      if: ${{ success() }}
-      env:
-        ALKILN_TAG_EXPRESSION: ${{ inputs.ALKILN_TAG_EXPRESSION || github.event.inputs.tags && format('{0}', github.event.inputs.tags) }}
-      shell: bash
-      run: |
-        log="💡 ALK0031 INFO: Run tests"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
-        alkiln-run "$ALKILN_TAG_EXPRESSION"
+    # # run tests
+    # - name: "💡 ALK0031 INFO: Run tests"
+    #   if: ${{ success() }}
+    #   env:
+    #     ALKILN_TAG_EXPRESSION: ${{ inputs.ALKILN_TAG_EXPRESSION || github.event.inputs.tags && format('{0}', github.event.inputs.tags) }}
+    #   shell: bash
+    #   run: |
+    #     log="💡 ALK0031 INFO: Run tests"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
+    #     alkiln-run "$ALKILN_TAG_EXPRESSION"
     
-    # on playground, delete project
-    - name: "💡 ALK0032 INFO: Delete the Project from the Playground"
-      if: ${{ always() && inputs.INSTALL_METHOD == 'playground' }}
-      shell: bash
-      run: |
-        log="💡 ALK0032 INFO: Delete the Project from the Playground"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
-        alkiln-takedown
+    # # on playground, delete project
+    # - name: "💡 ALK0032 INFO: Delete the Project from the Playground"
+    #   if: ${{ always() && inputs.INSTALL_METHOD == 'playground' }}
+    #   shell: bash
+    #   run: |
+    #     log="💡 ALK0032 INFO: Delete the Project from the Playground"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
+    #     alkiln-takedown
     
-    # Upload artifacts that subscribers can download on the Actions summary page
-    - name: "💡 ALK0033 INFO: Upload artifacts folder"
-      if: ${{ always() }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_FOLDER }}
-        path: ./alkiln-*
+    # # Upload artifacts that subscribers can download on the Actions summary page
+    # - name: "💡 ALK0033 INFO: Upload artifacts folder"
+    #   if: ${{ always() }}
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: ${{ env.ARTIFACT_FOLDER }}
+    #     path: ./alkiln-*
 
-    # Download artifacts folder internally to create action output
-    - name: "💡 ALK0183 INFO: Get uploaded artifacts folder"
-      if: ${{ always() }}
-      uses: actions/download-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_FOLDER }}
+    # # Download artifacts folder internally to create action output
+    # - name: "💡 ALK0183 INFO: Get uploaded artifacts folder"
+    #   if: ${{ always() }}
+    #   uses: actions/download-artifact@v4
+    #   with:
+    #     name: ${{ env.ARTIFACT_FOLDER }}
 
-    - name: "💡 ALK0184 INFO: Prepare ALKiln output file paths"
-      if: ${{ always() }}
-      id: alkiln_outputs
-      shell: bash
-      run: |
-        log="💡 ALK0184 INFO: Prepare ALKiln output file paths"
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}" && echo "$log"
+    # - name: "💡 ALK0184 INFO: Prepare ALKiln output file paths"
+    #   if: ${{ always() }}
+    #   id: alkiln_outputs
+    #   shell: bash
+    #   run: |
+    #     log="💡 ALK0184 INFO: Prepare ALKiln output file paths"
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}" && echo "$log"
 
-        FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
+    #     FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
 
-        log_folder="Test results artifacts folder is $FOLDER"
-        echo -e "\n$log_folder" >> "${{ env.DEBUG_PATH }}" && echo "$log_folder"
+    #     log_folder="Test results artifacts folder is $FOLDER"
+    #     echo -e "\n$log_folder" >> "${{ env.DEBUG_PATH }}" && echo "$log_folder"
 
-        if [[ "$FOLDER" = "" ]]; then
-          log_missing="Artifacts folder is missing. The path is an empty string: '$FOLDER'"
-          echo -e "\n$log_missing" >> "${{ env.DEBUG_PATH }}" && echo "$log_missing"
+    #     if [[ "$FOLDER" = "" ]]; then
+    #       log_missing="Artifacts folder is missing. The path is an empty string: '$FOLDER'"
+    #       echo -e "\n$log_missing" >> "${{ env.DEBUG_PATH }}" && echo "$log_missing"
 
-        else
-          REPORT_PATH="${FOLDER}report.txt"
-          REPORT_LOG_PATH="${FOLDER}report_log.txt"
-          UNEXPECTED_RESULTS_PATH="${FOLDER}unexpected_results.txt"
-          DEBUG_LOG_PATH="${FOLDER}debug_log.txt"
+    #     else
+    #       REPORT_PATH="${FOLDER}report.txt"
+    #       REPORT_LOG_PATH="${FOLDER}report_log.txt"
+    #       UNEXPECTED_RESULTS_PATH="${FOLDER}unexpected_results.txt"
+    #       DEBUG_LOG_PATH="${FOLDER}debug_log.txt"
 
-          if [ -f "$REPORT_PATH" ]; then
-            echo -e "\n$REPORT_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_PATH exists"
-          else
-            echo -e "\n$REPORT_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_PATH is missing"
-            REPORT_PATH=""
-          fi
+    #       if [ -f "$REPORT_PATH" ]; then
+    #         echo -e "\n$REPORT_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_PATH exists"
+    #       else
+    #         echo -e "\n$REPORT_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_PATH is missing"
+    #         REPORT_PATH=""
+    #       fi
 
-          if [ -f "$REPORT_LOG_PATH" ]; then
-            echo -e "\n$REPORT_LOG_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_LOG_PATH exists"
-          else
-            echo -e "\n$REPORT_LOG_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_LOG_PATH is missing"
-            REPORT_LOG_PATH=""
-          fi
+    #       if [ -f "$REPORT_LOG_PATH" ]; then
+    #         echo -e "\n$REPORT_LOG_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_LOG_PATH exists"
+    #       else
+    #         echo -e "\n$REPORT_LOG_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$REPORT_LOG_PATH is missing"
+    #         REPORT_LOG_PATH=""
+    #       fi
 
-          if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then
-            echo -e "\n$UNEXPECTED_RESULTS_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$UNEXPECTED_RESULTS_PATH exists"
-          else
-            echo -e "\n$UNEXPECTED_RESULTS_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$UNEXPECTED_RESULTS_PATH is missing"
-            UNEXPECTED_RESULTS_PATH=""
-          fi
+    #       if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then
+    #         echo -e "\n$UNEXPECTED_RESULTS_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$UNEXPECTED_RESULTS_PATH exists"
+    #       else
+    #         echo -e "\n$UNEXPECTED_RESULTS_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$UNEXPECTED_RESULTS_PATH is missing"
+    #         UNEXPECTED_RESULTS_PATH=""
+    #       fi
 
-          if [ -f "$DEBUG_LOG_PATH" ]; then
-            echo -e "\n$DEBUG_LOG_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$DEBUG_LOG_PATH exists"
-          else
-            echo -e "\n$DEBUG_LOG_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$DEBUG_LOG_PATH is missing"
-            DEBUG_LOG_PATH=""
-          fi
+    #       if [ -f "$DEBUG_LOG_PATH" ]; then
+    #         echo -e "\n$DEBUG_LOG_PATH exists" >> "${{ env.DEBUG_PATH }}" && echo "$DEBUG_LOG_PATH exists"
+    #       else
+    #         echo -e "\n$DEBUG_LOG_PATH is missing" >> "${{ env.DEBUG_PATH }}" && echo "$DEBUG_LOG_PATH is missing"
+    #         DEBUG_LOG_PATH=""
+    #       fi
 
-        fi
+    #     fi
 
-        echo "PATH_TO_ARTIFACTS=$FOLDER" >> "$GITHUB_OUTPUT"
-        echo "PATH_TO_REPORT_FILE=$REPORT_PATH" >> "$GITHUB_OUTPUT"
-        echo "PATH_TO_REPORT_LOG_FILE=$REPORT_LOG_PATH" >> "$GITHUB_OUTPUT"
-        echo "PATH_TO_UNEXPECTED_RESULTS_FILE=$UNEXPECTED_RESULTS_PATH" >> "$GITHUB_OUTPUT"
-        echo "PATH_TO_DEBUG_LOG_FILE=$DEBUG_LOG_PATH" >> "$GITHUB_OUTPUT"
+    #     echo "PATH_TO_ARTIFACTS=$FOLDER" >> "$GITHUB_OUTPUT"
+    #     echo "PATH_TO_REPORT_FILE=$REPORT_PATH" >> "$GITHUB_OUTPUT"
+    #     echo "PATH_TO_REPORT_LOG_FILE=$REPORT_LOG_PATH" >> "$GITHUB_OUTPUT"
+    #     echo "PATH_TO_UNEXPECTED_RESULTS_FILE=$UNEXPECTED_RESULTS_PATH" >> "$GITHUB_OUTPUT"
+    #     echo "PATH_TO_DEBUG_LOG_FILE=$DEBUG_LOG_PATH" >> "$GITHUB_OUTPUT"
 
-    # Avoid creating output from text in files
-    # Cannot properly create outputs with multi-line text. Collapses onto one line.
+    # # Avoid creating output from text in files
+    # # Cannot properly create outputs with multi-line text. Collapses onto one line.
 
-    - shell: bash
-      if: ${{ always() }}
-      run: |
-        log="💡 ALK0034 INFO: ALkiln finished running tests. See above for more details."
-        echo -e "\n$log" >> "${{ env.DEBUG_PATH }}" && echo "$log"
+    # - shell: bash
+    #   if: ${{ always() }}
+    #   run: |
+    #     log="💡 ALK0034 INFO: ALkiln finished running tests. See above for more details."
+    #     echo -e "\n$log" >> "${{ env.DEBUG_PATH }}" && echo "$log"
