Fix LLM code, add logs and codes...
Caveat: This was cherry-picked from another branch, so some of the commits and
changes mentioned below were removed as they were not relevant to this branch.
You can see the original context of the original LLM code in
https://github.com/SuffolkLITLab/ALKiln/pull/1079.

Thank you to @fractalkitty and @jamesnvc for consulting on puppeteer chrome
executable behavior.

Fixed:

- Browser-finding `else` code starts tests that then error because they couldn't
  find a browser.
- Browser-finding code was unnecessarily duplicated.
- Folder handling arbitrarily chooses the first folder.
- Folder handling causes the artifacts folder to itself contain 2 folders, thus
  causing potential errors or incorrect feedback to consumers, who would get
  "missing paths."
- Folder handling hides the current folder path error, but doesn't solve the
  root cause.
- ~~Internal testing flag is using the wrong type. The LLM didn't cause this,
  but it also didn't account for this.~~
- Left out informative logs.

~~I decided to keep the internal tests flag values because this will require
publishing a new version to npm, which we will have to test.~~

Co-authored-by: fractalkitty <72811467+fractalkitty@users.noreply.github.com>
Co-authored-by: Jamie Cash <james.cash@occasionallycogent.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -122,18 +122,24 @@ runs:
         log="💡 ALK0026 INFO: Install ALKiln directly from npm"
         echo -e "\n$log" >> "${{ env.DEBUG_PATH }}"
         npm install -g "@suffolklitlab/alkiln@$ALKILN_VERSION"
+
         BROWSER="$(
           command -v google-chrome-stable ||
           command -v google-chrome ||
+          command -v chrome ||
           command -v chromium-browser ||
           command -v chromium ||
           true
         )"
         if [[ -n "$BROWSER" ]]; then
+          log_result="💡 ALK0279 INFO: Found puppeteer browser executable at '$BROWSER'"
+          echo -e "\n$log_result" >> "${{ env.DEBUG_PATH }}" && echo -e "$log_result"
           echo "PUPPETEER_EXECUTABLE_PATH=$BROWSER" >> "$GITHUB_ENV"
         else
-          rm -rf "$HOME/.cache/puppeteer"
-          node "$(npm root -g)/@suffolklitlab/alkiln/node_modules/puppeteer/install.mjs"
+          log_result="🤕 ALK0280 INFO: Unable to find puppeteer browser executable"
+          echo -e "\n$log_result" >> "${{ env.DEBUG_PATH }}" && echo -e "$log_result"
+          # Our project uses bash error codes in the 50's. This may change.
+          exit 51
         fi
 
     # Files prep
@@ -227,7 +233,7 @@ runs:
         log="💡 ALK0184 INFO: Prepare ALKiln output file paths"
         echo -e "\n$log" >> "${{ env.DEBUG_PATH }}" && echo "$log"
 
-        FOLDER="$(ls -dt alkiln-*/ 2>/dev/null | head -n 1 || true)"
+        FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
 
         log_folder="Test results artifacts folder is $FOLDER"
         echo -e "\n$log_folder" >> "${{ env.DEBUG_PATH }}" && echo "$log_folder"
