Try to avoid an error due to an empty directory

diff --git a/.github/workflows/github_server.yml b/.github/workflows/github_server.yml
--- a/.github/workflows/github_server.yml
+++ b/.github/workflows/github_server.yml
@@ -59,6 +59,10 @@ jobs:
           # Set initial status code
           echo "AL_SERVER_STATUS=Good" >> $GITHUB_ENV
 
+      # Test failing to see what happens with issue creation
+      - run: exit 55
+        shell: bash
+
       - name: ALKiln - Start the isolated temporary docassemble server on GitHub
         id: github_server
         #### Developer note: you'll need to replace `uses: ./action_for_github_server`
@@ -73,10 +77,6 @@ jobs:
           #### Developer note: You can probably leave this out
           CONFIG_CONTENTS: "${{ secrets.CONFIG_CONTENTS }}"
       - run: echo "ALKiln finished starting the isolated GitHub docassemble server"
-        shell: bash
-
-      # Test failing to see what happens with issue creation
-      - run: exit 55
         shell: bash
 
       - shell: bash
@@ -133,6 +133,7 @@ jobs:
         run: echo "AL_SERVER_STATUS=Tests failed" >> $GITHUB_ENV
 
       #### Developer note: Example of making an issue when tests fail
+      #### See https://cli.github.com/manual/gh_issue_create for more details
       # if: ${{ failure() && env.AL_SERVER_STATUS == 'Tests failed' }}  # only for test failure
       - shell: bash
         if: ${{ failure() }}
@@ -143,21 +144,32 @@ jobs:
           # Make an issue with file contents or 'no file' message as part of the body
           echo '1'
 
-          # ex: "alkiln-2024-05-23 at 10h35m08sUTC/"
-          FOLDER=$(ls -d */ | grep -E '^alkiln-*')
-          echo "$FOLDER"
+          # Check if directory exists at all. If not,
+          # something other than the tests went wrong
+          FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
+
+          # exit_status=$?
+
+          # if [ $exit_status -ne 0 ]; then
+          #   FOLDER=""
+          # else
+          #   # ex: "alkiln-2024-05-23 at 10h35m08sUTC/"
+          #   FOLDER=$(ls -d */ | grep -E '^alkiln-*')
+          # fi
+
+          echo "Folder is $FOLDER"
 
           # Tests that failed or had typos in the Step instructions
           UNEXPECTED_RESULTS_PATH="${FOLDER}unexpected_results.txt"
+          echo "$UNEXPECTED_RESULTS_PATH"
           # Other possibly useful files
           # REPORT_PATH="${FOLDER}report.txt"
           # DEBUG_LOG_PATH="${FOLDER}debug_log.txt"
-          echo "$UNEXPECTED_RESULTS_PATH"
 
-          if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then \
-            UNEXPECTED_RESULTS=$(cat "$UNEXPECTED_RESULTS_PATH") \
-          else \
-            UNEXPECTED_RESULTS="unexpected_results.txt does not exist. Something other than the tests may have failed." \
+          if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then
+            UNEXPECTED_RESULTS=$(cat "$UNEXPECTED_RESULTS_PATH")
+          else
+            UNEXPECTED_RESULTS="unexpected_results.txt does not exist. Something other than the tests may have failed."
           fi
           echo "$UNEXPECTED_RESULTS"
 
