Fix missing $, comment out old code, adjust report for md format

diff --git a/.github/workflows/github_server.yml b/.github/workflows/github_server.yml
--- a/.github/workflows/github_server.yml
+++ b/.github/workflows/github_server.yml
@@ -54,10 +54,19 @@ jobs:
       # relative paths to action files
       - uses: actions/checkout@v4
 
-      - shell: bash
-        run: |
-          # Set initial status code
-          echo "AL_SERVER_STATUS=Good" >> $GITHUB_ENV
+
+
+
+
+      # $$$$$$$$$$$$$$$
+      # - shell: bash
+      #   run: |
+      #     # Set initial status code
+      #     echo "AL_SERVER_STATUS=Good" >> $GITHUB_ENV
+
+
+
+
 
       ## Test failing to see what happens with issue creation
       #- run: exit 55
@@ -79,9 +88,9 @@ jobs:
       - run: echo "ALKiln finished starting the isolated GitHub docassemble server"
         shell: bash
 
-      - shell: bash
-        if: ${{ failure() }}
-        run: echo "AL_SERVER_STATUS=Server setup failed" >> $GITHUB_ENV
+      # - shell: bash
+      #   if: ${{ failure() }}
+      #   run: echo "AL_SERVER_STATUS=Server setup failed" >> $GITHUB_ENV
 
       # #### Developer note: You can probably leave this out
       # # Optional debugging to explore things like docker issues
@@ -128,9 +137,9 @@ jobs:
           ALKILN_TAG_EXPRESSION: "${{ env.ALKILN_TAG_EXPRESSION }}"
           ALKILN_VERSION: output
 
-      - shell: bash
-        if: ${{ failure() && env.AL_SERVER_STATUS == 'Good' }}  # only if not already failed
-        run: echo "AL_SERVER_STATUS=Tests failed" >> $GITHUB_ENV
+      # - shell: bash
+      #   if: ${{ failure() && env.AL_SERVER_STATUS == 'Good' }}  # only if not already failed
+      #   run: echo "AL_SERVER_STATUS=Tests failed" >> $GITHUB_ENV
 
       #### Developer note: Example of making an issue when tests fail
       #### See https://cli.github.com/manual/gh_issue_create for more details
@@ -145,48 +154,49 @@ jobs:
           PATH_TO_DEBUG_LOG_FILE: "${{ steps.alkiln.outputs.PATH_TO_DEBUG_LOG_FILE }}"
         run: |
           # Make an issue with file contents or 'no file' message as part of the body
-          echo '1'
 
-          # Check if directory exists at all. If not,
-          # something other than the tests went wrong
-          FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
+          # echo '1'
 
-          # exit_status=$?
+          # # Check if directory exists at all. If not,
+          # # something other than the tests went wrong
+          # FOLDER=$(ls -d */ | grep -E '^alkiln-*' || true)
 
-          # if [ $exit_status -ne 0 ]; then
-          #   FOLDER=""
+          # # exit_status=$?
+
+          # # if [ $exit_status -ne 0 ]; then
+          # #   FOLDER=""
+          # # else
+          # #   # ex: "alkiln-2024-05-23 at 10h35m08sUTC/"
+          # #   FOLDER=$(ls -d */ | grep -E '^alkiln-*')
+          # # fi
+
+          # echo "Folder is $FOLDER"
+
+          # # Tests that failed or had typos in the Step instructions
+          # UNEXPECTED_RESULTS_PATH="${FOLDER}unexpected_results.txt"
+          # echo "$UNEXPECTED_RESULTS_PATH"
+          # # Other possibly useful files
+          # # REPORT_PATH="${FOLDER}report.txt"
+          # # DEBUG_LOG_PATH="${FOLDER}debug_log.txt"
+
+          # if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then
+          #   UNEXPECTED_RESULTS=$(cat "$UNEXPECTED_RESULTS_PATH")
           # else
-          #   # ex: "alkiln-2024-05-23 at 10h35m08sUTC/"
-          #   FOLDER=$(ls -d */ | grep -E '^alkiln-*')
+          #   UNEXPECTED_RESULTS="unexpected_results.txt does not exist. Something other than the tests may have failed."
           # fi
+          # #echo "UNEXPECTED_RESULTS is $UNEXPECTED_RESULTS"
 
-          echo "Folder is $FOLDER"
+          # gh issue create --body "An ALKiln test run failed. See the action at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
 
-          # Tests that failed or had typos in the Step instructions
-          UNEXPECTED_RESULTS_PATH="${FOLDER}unexpected_results.txt"
-          echo "$UNEXPECTED_RESULTS_PATH"
-          # Other possibly useful files
-          # REPORT_PATH="${FOLDER}report.txt"
-          # DEBUG_LOG_PATH="${FOLDER}debug_log.txt"
+          # ### Results:
 
-          if [ -f "$UNEXPECTED_RESULTS_PATH" ]; then
-            UNEXPECTED_RESULTS=$(cat "$UNEXPECTED_RESULTS_PATH")
-          else
-            UNEXPECTED_RESULTS="unexpected_results.txt does not exist. Something other than the tests may have failed."
-          fi
-          #echo "UNEXPECTED_RESULTS is $UNEXPECTED_RESULTS"
+          # $UNEXPECTED_RESULTS" --repo "$GITHUB_REPOSITORY" --label "testing" --title "Parse file in outer workflow 1 internal: Test if failed tests make issue"
 
-          gh issue create --body "An ALKiln test run failed. See the action at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
-
-          ### Results:
-
-          $UNEXPECTED_RESULTS" --repo "$GITHUB_REPOSITORY" --label "testing" --title "Parse file in outer workflow 1 internal: Test if failed tests make issue"
-
-          echo "10"
+          # echo "10"
 
           #####################################################
           # Version that uses the ALKiln step output file names
-          if [ -f "PATH_TO_UNEXPECTED_RESULTS_FILE" ]; then
+          if [ -f "$PATH_TO_UNEXPECTED_RESULTS_FILE" ]; then
             UNEXPECTED_2=$(cat "$PATH_TO_UNEXPECTED_RESULTS_FILE")
           else
             UNEXPECTED_2="unexpected_results.txt does not exist. Something other than the tests may have failed."
@@ -203,6 +213,6 @@ jobs:
           echo "101"
 
 
-      - shell: bash
-        if: ${{ failure() && env.AL_SERVER_STATUS == 'Good' }}  # only if not already failed
-        run: echo "AL_SERVER_STATUS=Issue creation failed" >> $GITHUB_ENV
+      # - shell: bash
+      #   if: ${{ failure() && env.AL_SERVER_STATUS == 'Good' }}  # only if not already failed
+      #   run: echo "AL_SERVER_STATUS=Issue creation failed" >> $GITHUB_ENV
